// i18n.js - Internationalization support for spending report
// Supports: English (en), Turkish (tr)

(function() {
    'use strict';

    // Translation strings
    const translations = {
        en: {
            // Report title and header
            reportTitle: '{year} Spending Report',
            dataFrom: 'Data from {sources}',
            
            // Theme toggle
            switchToLight: 'Switch to light mode',
            switchToDark: 'Switch to dark mode',
            
            // Search and filters
            searchPlaceholder: 'Search merchants, categories, locations...',
            dateFilter: '+ Date filter',
            months: 'Individual Months',
            clearAll: 'Clear all',
            searchTransactions: 'Search transactions: "{query}"',
            
            // Help section
            helpTitle: 'How to Read This Report',
            helpCategories: 'Categories:',
            helpCategoriesDesc: 'Merchants are grouped by their assigned category from merchant_categories.csv',
            helpTerms: 'Terms:',
            helpYtdDesc: 'year-to-date total',
            helpCountDesc: 'number of transactions',
            helpFilters: 'Filters:',
            helpFiltersDesc: 'Click on categories, tags, or locations to filter. Use search to find specific merchants.',
            
            // Summary cards
            totalSpending: 'Total Spending (YTD)',
            creditsApplied: 'Credits Applied',
            uncategorized: 'Uncategorized',
            cashFlow: 'Cash Flow',
            income: 'Income',
            spending: 'Spending',
            transfers: 'Transfers',
            excluded: 'Excluded',
            notIncludedInSpending: 'Not included in spending',
            transactionCount: '{count} transactions',
            
            // Charts
            spendingTrends: 'Spending Trends',
            monthlyTrend: 'Monthly Spending Trend',
            monthlySpending: 'Monthly Spending',
            byCategory: 'Spending by Category',
            categoryTrends: 'Category Trends by Month',
            
            // View toggle
            byView: 'By View',
            
            // Table headers
            merchant: 'Merchant',
            source: 'Source',
            category: 'Category',
            subcategory: 'Subcategory',
            count: 'Count',
            tags: 'Tags',
            total: 'Total',
            amount: 'Amount',
            
            // Table content
            refund: 'REFUND',
            
            // Match info popup
            whyThisMatched: 'Why This Matched',
            merchantPattern: 'Merchant Pattern',
            assignedTo: 'Assigned To',
            viewFilter: 'View Filter',
            fromSource: 'From',
            transactionDetails: 'Transaction Details',
            
            // Credits section
            totalCredits: 'Total Credits',
            reducedSpending: '(reduced spending)',
            
            // Excluded section
            notIncluded: '(not included in spending)',
            
            // Footer
            generatedBy: 'Generated by tally',
            dataThrough: 'Data through {date}',
            present: 'present',
            
            // Months (short)
            monthsShort: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
            
            // Per month suffix
            perMonth: '/mo'
        },
        tr: {
            // Rapor başlığı ve header
            reportTitle: '{year} Harcama Raporu',
            dataFrom: '{sources} verilerinden',
            
            // Tema değiştirme
            switchToLight: 'Açık temaya geç',
            switchToDark: 'Koyu temaya geç',
            
            // Arama ve filtreler
            searchPlaceholder: 'Satıcı, kategori, konum ara...',
            dateFilter: '+ Tarih filtresi',
            months: 'Aylar',
            clearAll: 'Tümünü temizle',
            searchTransactions: 'İşlemlerde ara: "{query}"',
            
            // Yardım bölümü
            helpTitle: 'Bu Raporu Nasıl Okuyabilirim',
            helpCategories: 'Kategoriler:',
            helpCategoriesDesc: 'Satıcılar merchant_categories.csv dosyasındaki kategorilere göre gruplandırılmıştır',
            helpTerms: 'Terimler:',
            helpYtdDesc: 'yıl başından bugüne toplam',
            helpCountDesc: 'işlem sayısı',
            helpFilters: 'Filtreler:',
            helpFiltersDesc: 'Filtrelemek için kategorilere, etiketlere veya konumlara tıklayın. Belirli satıcıları bulmak için arama kullanın.',
            
            // Özet kartları
            totalSpending: 'Toplam Harcama (YTD)',
            creditsApplied: 'Uygulanan İadeler',
            uncategorized: 'Kategorisiz',
            cashFlow: 'Nakit Akışı',
            income: 'Gelir',
            spending: 'Harcama',
            transfers: 'Transferler',
            excluded: 'Hariç Tutulan',
            notIncludedInSpending: 'Harcamaya dahil değil',
            transactionCount: '{count} işlem',
            
            // Grafikler
            spendingTrends: 'Harcama Trendleri',
            monthlyTrend: 'Aylık Harcama Trendi',
            monthlySpending: 'Aylık Harcama',
            byCategory: 'Kategoriye Göre Harcama',
            categoryTrends: 'Aylık Kategori Trendleri',
            
            // Görünüm değiştirme
            byView: 'Görünüme Göre',
            
            // Tablo başlıkları
            merchant: 'Satıcı',
            source: 'Kaynak',
            category: 'Kategori',
            subcategory: 'Alt Kategori',
            count: 'Adet',
            tags: 'Etiketler',
            total: 'Toplam',
            amount: 'Tutar',
            
            // Tablo içeriği
            refund: 'İADE',
            
            // Eşleşme bilgisi popup
            whyThisMatched: 'Neden Eşleşti',
            merchantPattern: 'Satıcı Deseni',
            assignedTo: 'Atanan',
            viewFilter: 'Görünüm Filtresi',
            fromSource: 'Kaynak',
            transactionDetails: 'İşlem Detayları',
            
            // Krediler bölümü
            totalCredits: 'Toplam İade',
            reducedSpending: '(harcamayı azalttı)',
            
            // Hariç tutulan bölümü
            notIncluded: '(harcamaya dahil değil)',
            
            // Alt bilgi
            generatedBy: 'Tally ile oluşturuldu',
            dataThrough: '{date} tarihine kadar veri',
            present: 'güncel',
            
            // Aylar (kısa)
            monthsShort: ['Oca', 'Şub', 'Mar', 'Nis', 'May', 'Haz', 'Tem', 'Ağu', 'Eyl', 'Eki', 'Kas', 'Ara'],
            
            // Aylık eki
            perMonth: '/ay'
        }
    };

    // Currency formatting by language
    const currencyFormats = {
        en: {
            format: (amount, customFormat) => {
                const formatted = Math.round(Math.abs(amount)).toLocaleString('en-US');
                if (customFormat) {
                    return customFormat.replace('{amount}', formatted);
                }
                return '$' + formatted;
            },
            formatAxis: (value, customFormat) => {
                if (customFormat) {
                    return customFormat.replace('{amount}', value);
                }
                return '$' + value;
            }
        },
        tr: {
            format: (amount, customFormat) => {
                const formatted = Math.round(Math.abs(amount)).toLocaleString('tr-TR');
                if (customFormat) {
                    return customFormat.replace('{amount}', formatted);
                }
                return formatted + ' ₺';
            },
            formatAxis: (value, customFormat) => {
                if (customFormat) {
                    return customFormat.replace('{amount}', value.toLocaleString('tr-TR'));
                }
                return value.toLocaleString('tr-TR') + ' ₺';
            }
        }
    };

    // Get current language from spending data
    function getLanguage() {
        return (window.spendingData && window.spendingData.language) || 'en';
    }

    // Get custom currency format from spending data
    function getCurrencyFormat() {
        return window.spendingData && window.spendingData.currencyFormat;
    }

    // Translation function with parameter interpolation
    function t(key, params) {
        const lang = getLanguage();
        const strings = translations[lang] || translations.en;
        let text = strings[key] || translations.en[key] || key;
        
        if (params) {
            for (const [k, v] of Object.entries(params)) {
                text = text.replace(new RegExp(`\\{${k}\\}`, 'g'), v);
            }
        }
        
        return text;
    }

    // Get short month name by index (0-11)
    function getMonthShort(idx) {
        const lang = getLanguage();
        const strings = translations[lang] || translations.en;
        const months = strings.monthsShort || translations.en.monthsShort;
        return months[idx] || '';
    }

    // Format currency amount (no decimals)
    function formatCurrency(amount) {
        const lang = getLanguage();
        const formatter = currencyFormats[lang] || currencyFormats.en;
        return formatter.format(amount, getCurrencyFormat());
    }

    // Format currency for chart axis
    function formatCurrencyAxis(value) {
        const lang = getLanguage();
        const formatter = currencyFormats[lang] || currencyFormats.en;
        return formatter.formatAxis(value, getCurrencyFormat());
    }

    // Get per-month formatted string (accepts formatted currency)
    function getPerMonth(formattedAmount) {
        const lang = getLanguage();
        const strings = translations[lang] || translations.en;
        const suffix = strings.perMonth || '/mo';
        return formattedAmount + suffix;
    }

    // Export to window
    window.i18n = {
        t,
        getMonthShort,
        formatCurrency,
        formatCurrencyAxis,
        getPerMonth,
        getLanguage,
        translations
    };
})();
