// i18n.js - Internationalization support for spending report
// Supports: English (en), Turkish (tr)

(function() {
    'use strict';

    // Translation strings
    const translations = {
        en: {
            // Report title and header
            reportTitle: '{year} Spending Report',
            dataFrom: 'Data from {sources}',
            
            // Theme toggle
            switchToLight: 'Switch to light theme',
            switchToDark: 'Switch to dark theme',
            
            // Search and filters
            searchPlaceholder: 'Search merchants, categories, tags...',
            dateFilter: 'Date filter',
            months: 'Months',
            clearAll: 'Clear all',
            searchTransactions: 'Search transactions for: "{query}"',
            
            // Help section
            howToRead: 'How to read this report',
            categoriesLabel: 'Categories',
            helpCategories: 'Click headers to collapse/expand. Click dots to filter.',
            termsLabel: 'Terms',
            helpTerms: '<b>/mo</b> = monthly average &nbsp; <b>%</b> = percent of total',
            filtersLabel: 'Filters',
            helpFilters: 'Click chips to toggle include/exclude. Click × to remove.',
            
            // Summary cards
            totalSpending: 'Total Spending',
            creditsApplied: 'Credits Applied',
            uncategorized: 'Uncategorized',
            cashFlow: 'Cash Flow',
            income: 'Income',
            spending: 'Spending',
            transfers: 'Transfers',
            excluded: 'Excluded',
            notIncludedInSpending: 'Not included in spending',
            transactions: 'transactions',
            
            // Charts
            spendingTrends: 'Spending Trends',
            monthlySpendingTrend: 'Monthly Spending Trend',
            monthlySpending: 'Monthly Spending',
            spendingByCategory: 'Spending by Category',
            categoryTrendsByMonth: 'Category Trends by Month',
            
            // View toggle
            byCategory: 'By Category',
            byView: 'By View',
            
            // Table headers
            merchant: 'Merchant',
            source: 'Source',
            category: 'Category',
            subcategory: 'Subcategory',
            count: 'Count',
            tags: 'Tags',
            total: 'Total',
            amount: 'Amount',
            
            // Table content
            refund: 'refund',
            
            // Match info popup
            whyMatched: 'Why This Matched',
            merchantPattern: 'Merchant Pattern',
            assignedTo: 'Assigned To',
            viewFilter: 'View Filter',
            fromSource: 'Source',
            
            // Credits section
            creditsTitle: 'Credits Applied',
            creditsTotalLabel: 'Total Credits',
            creditsSubtitle: '(reduced spending)',
            
            // Excluded section
            excludedTitle: 'Excluded',
            excludedSubtitle: '(not included in spending)',
            
            // Footer
            generatedBy: 'Generated by Tally',
            dataThrough: 'Data through {date}',
            present: 'present',
            
            // Months (short)
            monthsShort: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
            
            // Per month suffix
            perMonth: '/mo'
        },
        tr: {
            // Rapor başlığı ve header
            reportTitle: '{year} Harcama Raporu',
            dataFrom: '{sources} verilerinden',
            
            // Tema değiştirme
            switchToLight: 'Açık temaya geç',
            switchToDark: 'Koyu temaya geç',
            
            // Arama ve filtreler
            searchPlaceholder: 'Satıcı, kategori, etiket ara...',
            dateFilter: 'Tarih filtresi',
            months: 'Aylar',
            clearAll: 'Tümünü temizle',
            searchTransactions: 'İşlemlerde ara: "{query}"',
            
            // Yardım bölümü
            howToRead: 'Bu raporu nasıl okuyabilirim',
            categoriesLabel: 'Kategoriler',
            helpCategories: 'Başlıklara tıklayarak daraltın/genişletin. Noktalara tıklayarak filtreleyin.',
            termsLabel: 'Terimler',
            helpTerms: '<b>/ay</b> = aylık ortalama &nbsp; <b>%</b> = toplama yüzdesi',
            filtersLabel: 'Filtreler',
            helpFilters: 'Dahil et/hariç tut için çiplere tıklayın. Kaldırmak için × tıklayın.',
            
            // Özet kartları
            totalSpending: 'Toplam Harcama',
            creditsApplied: 'Uygulanan İadeler',
            uncategorized: 'Kategorisiz',
            cashFlow: 'Nakit Akışı',
            income: 'Gelir',
            spending: 'Harcama',
            transfers: 'Transferler',
            excluded: 'Hariç Tutulan',
            notIncludedInSpending: 'Harcamaya dahil değil',
            transactions: 'işlem',
            
            // Grafikler
            spendingTrends: 'Harcama Trendleri',
            monthlySpendingTrend: 'Aylık Harcama Trendi',
            monthlySpending: 'Aylık Harcama',
            spendingByCategory: 'Kategoriye Göre Harcama',
            categoryTrendsByMonth: 'Aylık Kategori Trendleri',
            
            // Görünüm değiştirme
            byCategory: 'Kategoriye Göre',
            byView: 'Görünüme Göre',
            
            // Tablo başlıkları
            merchant: 'Satıcı',
            source: 'Kaynak',
            category: 'Kategori',
            subcategory: 'Alt Kategori',
            count: 'Adet',
            tags: 'Etiketler',
            total: 'Toplam',
            amount: 'Tutar',
            
            // Tablo içeriği
            refund: 'iade',
            
            // Eşleşme bilgisi popup
            whyMatched: 'Neden Eşleşti',
            merchantPattern: 'Satıcı Deseni',
            assignedTo: 'Atanan',
            viewFilter: 'Görünüm Filtresi',
            fromSource: 'Kaynak',
            
            // Krediler bölümü
            creditsTitle: 'Uygulanan İadeler',
            creditsTotalLabel: 'Toplam İade',
            creditsSubtitle: '(harcamayı azalttı)',
            
            // Hariç tutulan bölümü
            excludedTitle: 'Hariç Tutulan',
            excludedSubtitle: '(harcamaya dahil değil)',
            
            // Alt bilgi
            generatedBy: 'Tally ile oluşturuldu',
            dataThrough: '{date} tarihine kadar veri',
            present: 'güncel',
            
            // Aylar (kısa)
            monthsShort: ['Oca', 'Şub', 'Mar', 'Nis', 'May', 'Haz', 'Tem', 'Ağu', 'Eyl', 'Eki', 'Kas', 'Ara'],
            
            // Aylık eki
            perMonth: '/ay'
        }
    };

    // Currency formatting by language
    const currencyFormats = {
        en: {
            // Default USD format, can be overridden by spendingData.currencyFormat
            format: (amount, customFormat) => {
                const formatted = Math.round(Math.abs(amount)).toLocaleString('en-US');
                if (customFormat) {
                    return customFormat.replace('{amount}', formatted);
                }
                return '$' + formatted;
            },
            formatAxis: (value, customFormat) => {
                if (customFormat) {
                    return customFormat.replace('{amount}', value);
                }
                return '$' + value;
            }
        },
        tr: {
            format: (amount, customFormat) => {
                const formatted = Math.round(Math.abs(amount)).toLocaleString('tr-TR');
                if (customFormat) {
                    return customFormat.replace('{amount}', formatted);
                }
                return formatted + ' ₺';
            },
            formatAxis: (value, customFormat) => {
                if (customFormat) {
                    return customFormat.replace('{amount}', value.toLocaleString('tr-TR'));
                }
                return value.toLocaleString('tr-TR') + ' ₺';
            }
        }
    };

    // Get current language from spending data
    function getLanguage() {
        return (window.spendingData && window.spendingData.language) || 'en';
    }

    // Get custom currency format from spending data
    function getCurrencyFormat() {
        return window.spendingData && window.spendingData.currencyFormat;
    }

    // Translation function with parameter interpolation
    function t(key, params) {
        const lang = getLanguage();
        const strings = translations[lang] || translations.en;
        let text = strings[key] || translations.en[key] || key;
        
        // Interpolate parameters like {year}, {date}, etc.
        if (params) {
            for (const [k, v] of Object.entries(params)) {
                text = text.replace(new RegExp(`\\{${k}\\}`, 'g'), v);
            }
        }
        
        return text;
    }

    // Get short month name by index (0-11)
    function getMonthShort(idx) {
        const lang = getLanguage();
        const strings = translations[lang] || translations.en;
        const months = strings.monthsShort || translations.en.monthsShort;
        return months[idx] || '';
    }

    // Format currency amount (no decimals)
    function formatCurrency(amount) {
        const lang = getLanguage();
        const formatter = currencyFormats[lang] || currencyFormats.en;
        return formatter.format(amount, getCurrencyFormat());
    }

    // Format currency for chart axis (abbreviated)
    function formatCurrencyAxis(value) {
        const lang = getLanguage();
        const formatter = currencyFormats[lang] || currencyFormats.en;
        return formatter.formatAxis(value, getCurrencyFormat());
    }

    // Get per-month suffix
    function getPerMonth() {
        const lang = getLanguage();
        const strings = translations[lang] || translations.en;
        return strings.perMonth || '/mo';
    }

    // Export to window
    window.i18n = {
        t,
        getMonthShort,
        formatCurrency,
        formatCurrencyAxis,
        getPerMonth,
        getLanguage,
        translations // Expose for debugging
    };
})();
